<?php
// Variables
return [
  "creatorName" => "RyanJr",
  "creatorUrl" => "https://ryanjr.dev",
  "appName" => "JO Computer",
  "appSuffix" => "Marketplace",
  "appVersion" => "1.0.0",
  "appFree" => false,
  "appDescription" => "A robust Point of Sale (POS) application built with Laravel 12.",
  "appKeyword" => "jual beli komputer, servis komputer, toko komputer, rakit pc, cctv, kabel LAN, rj45, jo computer, komputer, computer, laptop, flashdisk, usb, ssd, ram, ecommerce, marketplace, indonesia",
  "productPage" => "https://jocomputer.com",
  "support" => "",
  "adminTemplates" => "",
  "ogTitle" => "JO Computer",
  "ogImage" => "",
  "ogType" => "website",
  "documentation" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "instagramUrl" => "",
  "linkedinUrl" => "",
  "youtubeUrl" => "",
];
