<?php
// Variables
return [
  "creatorName" => "Store Owner",
  "creatorUrl" => "https://example.com",
  "templateName" => "JO Computer",
  "templateSuffix" => "Point of Sale Management System",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "A robust Point of Sale (POS) application built with Laravel 12.",
  "templateKeyword" => "pos, point of sale, laravel pos, management system, dashboard",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "adminTemplates" => "",
  "bootstrapDashboard" => "",
  "ogTitle" => "JO Computer",
  "ogImage" => "",
  "ogType" => "website",
  "documentation" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => ""
];
